"""Alloy — a blended derivative-free optimizer for small budgets.

Provenance
----------
Alloy was not written by a person. It was generated by a language model
(claude-opus-4-8) at the equal-weights point of an "inspiration simplex"
whose vertices were Nelder-Mead, Differential Evolution, CMA-ES, pattern
search and simulated annealing: the prompt required a program blending all
five in equal proportion, part by part. The generated program was selected
on sixteen disguised objectives and then validated on twenty-nine problems
never used in any selection step (580 instances, budgets 60-480), where it
had the best mean rank at every budget and beat Nelder-Mead, Differential
Evolution, CMA-ES and Nevergrad's CMA pairwise on 64-77% of instances.
See papers/dfo_recommender/inspiration_simplex.tex; the verbatim generated
artifact is papers/dfo_recommender/runs/simplex_warm_code/centroid.py, and
this class is a line-faithful port of it onto BaseOptimizer.

A caveat worth recording: the continuous simplex search contributed little
beyond this point (the equal blend was the best recipe found), and
regenerations at the same recipe vary widely. Alloy is the validated draw.

Mechanism
---------
Initialise with a DE-style population; build a Nelder-Mead simplex from the
best members; at each step choose one of four move generators with equal
probability (NM reflect/expand/contract, DE mutation + crossover, Gaussian
perturbation with success-adapted diagonal covariance, Hooke-Jeeves
coordinate probe with shrinking step); gate every candidate through a
simulated-annealing acceptance rule with geometric cooling; on stagnation,
reheat and rebuild the simplex around the incumbent.
"""

import math
import random

from .base import BaseOptimizer


class Alloy(BaseOptimizer):
    """Equal blend of NM, DE, CMA-style, pattern search and SA mechanisms.

    Strongest at small evaluation budgets (roughly 60-480) on noisy or
    irregular objectives; see the module docstring for provenance and the
    out-of-sample evidence.
    """

    def optimize(self):
        n_dim = self.n_dim
        n_trials = self.n_trials
        if n_dim <= 0:
            return (self.evaluate([]) if n_trials > 0 else float("inf"), [])

        def clip(x):
            return [0.0 if xi < 0.0 else (1.0 if xi > 1.0 else xi) for xi in x]

        def feval(x):
            return self.evaluate(clip(x))

        def budget_left():
            return self.evaluations < n_trials

        # ---- init (DE graft): population ----
        pop_size = max(n_dim + 1, min(8 + 2 * n_dim, max(5, n_trials // 6)))
        pop, pop_f = [], []
        for _ in range(pop_size):
            if not budget_left():
                break
            x = [random.random() for _ in range(n_dim)]
            pop.append(x)
            pop_f.append(feval(x))
        if not pop:
            return (self.best_value, self.best_x)

        # Build initial simplex (host: Nelder-Mead) from best population members
        order = sorted(range(len(pop)), key=lambda i: pop_f[i])
        simplex = [pop[i][:] for i in order[: n_dim + 1]]
        simplex_f = [pop_f[i] for i in order[: n_dim + 1]]
        while len(simplex) < n_dim + 1 and budget_left():
            base = simplex[0][:]
            j = (len(simplex) - 1) % n_dim
            base[j] = min(1.0, base[j] + 0.1)
            simplex.append(base)
            simplex_f.append(feval(base))

        # ---- adaptation state ----
        step = 0.25
        sigma = 0.2
        cov_diag = [0.04] * n_dim
        F = 0.6
        CR = 0.9

        # ---- SA temperature (acceptance + restart) ----
        f_lo, f_hi = min(simplex_f), max(simplex_f)
        T0 = max(1e-6, (f_hi - f_lo) + 1e-3)
        T = T0

        def order_simplex():
            idx = sorted(range(len(simplex)), key=lambda i: simplex_f[i])
            return [simplex[i][:] for i in idx], [simplex_f[i] for i in idx]

        def centroid_of(pts, exclude):
            c = [0.0] * n_dim
            m = 0
            for i, p in enumerate(pts):
                if i == exclude:
                    continue
                for d in range(n_dim):
                    c[d] += p[d]
                m += 1
            return [ci / m for ci in c]

        def accept(f_new, f_old):
            if f_new <= f_old:
                return True
            if T <= 1e-12:
                return False
            try:
                return random.random() < math.exp(-(f_new - f_old) / T)
            except OverflowError:
                return False

        stagnation = 0
        while budget_left():
            simplex, simplex_f = order_simplex()
            worst_i = len(simplex) - 1
            best_x = simplex[0]
            worst_x = simplex[worst_i]
            worst_f = simplex_f[worst_i]
            cen = centroid_of(simplex, worst_i)

            r = random.random()
            improved = False

            if r < 0.25:
                # --- Nelder-Mead reflect / expand / contract / shrink ---
                refl = [cen[d] + 1.0 * (cen[d] - worst_x[d]) for d in range(n_dim)]
                if not budget_left():
                    break
                fr = feval(refl)
                if fr < simplex_f[0]:
                    exp = [cen[d] + 2.0 * (cen[d] - worst_x[d]) for d in range(n_dim)]
                    if budget_left():
                        fe = feval(exp)
                        cand, cf = (exp, fe) if fe < fr else (refl, fr)
                    else:
                        cand, cf = refl, fr
                elif fr < worst_f:
                    cand, cf = refl, fr
                else:
                    con = [cen[d] + 0.5 * (worst_x[d] - cen[d]) for d in range(n_dim)]
                    if budget_left():
                        fc = feval(con)
                        if fc < worst_f:
                            cand, cf = con, fc
                        else:
                            for i in range(1, len(simplex)):
                                if not budget_left():
                                    break
                                simplex[i] = [
                                    best_x[d] + 0.5 * (simplex[i][d] - best_x[d])
                                    for d in range(n_dim)
                                ]
                                simplex_f[i] = feval(simplex[i])
                            cand, cf = None, None
                    else:
                        cand, cf = None, None
                if cand is not None and accept(cf, worst_f):
                    simplex[worst_i] = clip(cand)
                    simplex_f[worst_i] = cf
                    if cf < worst_f:
                        improved = True

            elif r < 0.50:
                # --- Differential Evolution: rand/1 or current-to-best/1 ---
                idxs = list(range(len(simplex)))
                random.shuffle(idxs)
                a, b, c = idxs[0], idxs[1 % len(idxs)], idxs[2 % len(idxs)]
                target = worst_x
                if random.random() < 0.5:
                    mutant = [
                        simplex[a][d] + F * (simplex[b][d] - simplex[c][d])
                        for d in range(n_dim)
                    ]
                else:
                    mutant = [
                        target[d]
                        + F * (best_x[d] - target[d])
                        + F * (simplex[b][d] - simplex[c][d])
                        for d in range(n_dim)
                    ]
                jr = random.randrange(n_dim)
                trial = [
                    mutant[d] if (random.random() < CR or d == jr) else target[d]
                    for d in range(n_dim)
                ]
                if not budget_left():
                    break
                ft = feval(trial)
                if accept(ft, worst_f):
                    simplex[worst_i] = clip(trial)
                    simplex_f[worst_i] = ft
                    if ft < worst_f:
                        improved = True

            elif r < 0.75:
                # --- CMA-style Gaussian sampling with adaptive diagonal cov ---
                cand = [
                    best_x[d] + sigma * random.gauss(0.0, math.sqrt(cov_diag[d]))
                    for d in range(n_dim)
                ]
                if not budget_left():
                    break
                fc = feval(cand)
                if accept(fc, worst_f):
                    if fc < worst_f:
                        improved = True
                        for d in range(n_dim):
                            delta = cand[d] - best_x[d]
                            cov_diag[d] = 0.8 * cov_diag[d] + 0.2 * (
                                delta * delta + 1e-8
                            )
                    simplex[worst_i] = clip(cand)
                    simplex_f[worst_i] = fc

            else:
                # --- pattern search: Hooke-Jeeves coordinate probes ---
                cur = best_x[:]
                cur_f = simplex_f[0]
                base_f = cur_f
                for d in range(n_dim):
                    if not budget_left():
                        break
                    trial = cur[:]
                    trial[d] += step
                    ft = feval(trial)
                    if ft < cur_f:
                        cur, cur_f = clip(trial), ft
                    else:
                        if not budget_left():
                            break
                        trial = cur[:]
                        trial[d] -= step
                        ft = feval(trial)
                        if ft < cur_f:
                            cur, cur_f = clip(trial), ft
                if cur_f < base_f:
                    improved = True
                    if accept(cur_f, worst_f):
                        simplex[worst_i] = cur
                        simplex_f[worst_i] = cur_f
                else:
                    step *= 0.5
                    if step < 1e-6:
                        step = 0.25

            # ---- adaptation of global scales ----
            if improved:
                stagnation = 0
                sigma = min(0.5, sigma * 1.05)
            else:
                stagnation += 1
                sigma = max(1e-3, sigma * 0.97)

            # ---- SA cooling ----
            T *= 0.995
            if T < 1e-9:
                T = 1e-9

            # ---- SA-driven restart when stuck ----
            if stagnation > max(12, 4 * n_dim) and budget_left():
                stagnation = 0
                T = max(T0 * 0.5, T * 5.0)
                step = 0.25
                sigma = 0.2
                keep = list(self.best_x)
                simplex = [keep[:]]
                simplex_f = [self.best_value]
                for _ in range(n_dim):
                    if not budget_left():
                        break
                    p = [
                        min(1.0, max(0.0, keep[d] + random.uniform(-0.3, 0.3)))
                        for d in range(n_dim)
                    ]
                    simplex.append(p)
                    simplex_f.append(feval(p))
                while len(simplex) < n_dim + 1 and budget_left():
                    p = [random.random() for _ in range(n_dim)]
                    simplex.append(p)
                    simplex_f.append(feval(p))

        return (self.best_value, self.best_x)
